export type SecondaryLanguage = "zh" | "en";

const englishChoices: Record<string, string> = Object.assign({}, {
  "兩者相等": "They are equal",
  "0 上": "At 0",
  "有長度": "Has length",
  "有面積": "Has area",
  "有體積": "Has volume",
  "沒有位置": "No position",
  "沒有維度": "No dimension",
  "沒有角": "No angle",
  "沒有關係": "No relationship",
  "未知": "Unknown",
  "相加 90°": "Sum to 90°",
  "相加 180°": "Sum to 180°",
  "相加 360°": "Sum to 360°",
  "一半": "One half",
  "兩倍": "Twice",
  "雙倍": "Double",
  "不相關": "Not related",
  "完全一樣大": "Exactly the same size",
  "只有形狀相同": "Same shape only",
  "只有面積相同": "Same area only",
  "只有周界相同": "Same perimeter only",
  "只有角相同": "Same angles only",
  "比例不同": "Different proportions",
  "相乘": "Multiply",
  "相減": "Subtract",
  "平方": "Square",
  "方程": "Equation",
  "角": "Angle",
  "線段": "Line segment",
  "圓形": "Circle",
  "截面": "Cross-section",
  "對稱": "Symmetry",
  "平移": "Translation",
  "反射": "Reflection",
  "放大": "Enlargement",
  "縮小": "Reduction",
  "轉動": "Rotation",
  "滑動": "Slide",
  "翻轉": "Flip",
  "改變大小": "Change size",
  "鏡像翻轉": "Mirror reflection",
  "直線滑動": "Linear slide",
  "畫三角形": "Draw triangles",
  "解方程": "Solve equations",
  "量角器": "Protractor",
  "尺": "Ruler",
  "計算器": "Calculator",
  "量重量": "Measure mass",
  "圓面積": "Area of a circle",
  "立體體積": "Volume of a solid",
  "分數加法": "Addition of fractions",
  "角度和": "Sum of angles",
  "最大值": "Maximum value",
  "平均數": "Mean",
  "百分率": "Percentage",
  "第一象限": "Quadrant I",
  "第二象限": "Quadrant II",
  "第三象限": "Quadrant III",
  "第四象限": "Quadrant IV",
  "原點": "Origin",
  "x 軸": "x-axis",
  "平面圖形": "Plane figure",
  "立方體": "Cube",
  "無限": "Infinitely many",
  "都 是 0": "Both are 0",
  "都是 0": "Both are 0",
  "都是 1": "Both are 1",
  "必定不同": "Always different",
  "必定為三角形": "Must be a triangle",
  "不變": "No change",
  "變為四倍": "Becomes four times as large",
  "任何很大的數": "Any very large number",
  "百分率誤差": "Percentage error",
  "圖形的面積": "Area of a figure",
  "斜率": "Gradient",
  "截距": "Intercept",
  "圖像法": "Graphical method",
  "因式分解法": "Factorisation method",
  "試誤法": "Trial and error",
  "所有三角形": "All triangles",
  "正方形": "Square",
  "梯形": "Trapezium",
  "圓心": "Centre of a circle",
  "面": "Face",
  "棱": "Edge",
  "頂點": "Vertex",
  "表示平面角": "Represent plane angles",
  "表示數列": "Represent sequences",
  "表示統計圖": "Represent statistical charts",
  "以圓弧表示": "As arcs",
  "以垂直線表示": "As vertical lines",
  "不需要表示": "Need not be shown",
  "不需要刻度": "No scale is needed",
  "只使用圖案": "Use symbols only",
  "省略資料來源": "Omit the source",
  "誤導讀者": "Mislead readers",
  "只訪問朋友": "Survey friends only",
  "刪除不合意答案": "Delete unwanted responses",
  "只展示最高數值": "Show only the highest value",
  "結果必定準確": "Results are always accurate",
  "沒有影響": "No effect",
  "消除誤差": "Eliminate error",
  "增加樣本數目": "Increase the sample size",
  "樣本更多": "More samples",
  "平均數變大": "The mean becomes larger",
  "數據必定錯誤": "The data must be wrong",
  "圖表必定不美觀": "The chart must look unattractive",
  "柱形會消失": "The bars disappear",
  "資料會自動改變": "The data changes automatically",
  "顏色喜好": "Colour preference",
  "字體大小": "Font size",
  "頁碼": "Page number",
  "有理數": "Rational number",
  "無理數": "Irrational number",
  "整數": "Integer",
  "自然數": "Natural number",
  "有限小數": "Terminating decimal",
  "循環小數": "Recurring decimal",
  "最短的邊": "The shortest side",
  "θ 的對邊": "The side opposite θ",
  "θ 的鄰邊": "The side adjacent to θ",
  "對邊/斜邊": "Opposite over hypotenuse",
  "對邊/鄰邊": "Opposite over adjacent",
  "鄰邊/斜邊": "Adjacent over hypotenuse",
  "斜邊/對邊": "Hypotenuse over opposite",
  "斜邊/鄰邊": "Hypotenuse over adjacent",
  "y 坐標之和": "Sum of the y-coordinates",
  "兩個 x 坐標的乘積": "Product of the x-coordinates",
  "兩點的斜率": "Gradient of the two points",
  "互補": "Supplementary",
  "直角": "Right angle",
  "平行": "Parallel",
  "垂直": "Perpendicular",
  "垂直線": "Vertical line",
  "斜線": "Sloping line",
  "曲線": "Curve",
  "水平線向上": "Upward from the horizontal",
  "水平線向下": "Downward from the horizontal",
  "鉛直線": "Vertical line",
  "北方": "North",
  "東方": "East",
  "南方": "South",
  "西方": "West",
  "正東方向": "Due east",
  "正南方向": "Due south",
  "正西方向": "Due west",
  "中線": "Median",
  "高": "Altitude",
  "邊": "Side",
  "角平分線": "Angle bisector",
  "邊的垂直平分線": "Perpendicular bisector of a side",
  "原本金": "Original principal",
  "折扣額": "Discount amount",
  "虧損額": "Loss amount",
  "圖表顏色": "Chart colour",
  "中位數": "Median",
  "眾數": "Mode",
  "幾何平均數": "Geometric mean",
  "大於 1": "Greater than 1",
  "只標示 2": "Mark 2 only",
  "整條數線塗滿": "Shade the entire number line",
  "增加 3": "Increases by 3",
  "增加 1/3": "Increases by 1/3",
  "相乘為 −1": "Their product is −1",
  "相加為 0": "Their sum is 0",
  "底面半徑": "Base radius",
  "體積": "Volume",
  "球體表面積": "Surface area of a sphere",
  "有利結果 ÷ 所有理論結果": "Favourable outcomes ÷ all theoretical outcomes",
  "平均數 ÷ 眾數": "Mean ÷ mode",
  "樣本數 × 概率": "Sample size × probability",
}, {
  "3x 和 -2x": "3x and −2x",
  "3x 和 3y": "3x and 3y",
  "x 和 x²": "x and x²",
  "a 和 b": "a and b",
  "x 正 y 負": "x positive, y negative",
  "x 負 y 正": "x negative, y positive",
  "都是負數": "Both are negative",
  "長 × 闊": "Length × width",
  "底 × 高": "Base × height",
  "2 × 底 × 高": "2 × base × height",
  "一維": "One-dimensional",
  "四維": "Four-dimensional",
  "立體體積": "Volume of a solid",
  "圓面積": "Area of a circle",
  "分數加法": "Addition of fractions",
  "角度和": "Sum of angles",
  "量度": "Measurement",
  "沒有影響": "No effect",
  "相交且垂直": "Intersecting and perpendicular",
  "平方": "Square",
  "有理數": "Rational number",
  "無理數": "Irrational number",
  "整數": "Integer",
  "自然數": "Natural number",
  "有限小數": "Terminating decimal",
  "循環小數": "Recurring decimal",
  "任何很大的數": "Any very large number",
  "百分率誤差": "Percentage error",
  "圖形的面積": "Area of a figure",
  "方程組的解": "Solution of the system",
  "代入法": "Substitution",
  "圖像法": "Graphical method",
  "因式分解法": "Factorisation method",
  "試誤法": "Trial and error",
  "所有三角形": "All triangles",
  "直角三角形": "Right-angled triangle",
  "圓形": "Circle",
  "正方形": "Square",
  "梯形": "Trapezium",
  "最短的邊": "Shortest side",
  "θ 的對邊": "Side opposite θ",
  "θ 的鄰邊": "Side adjacent to θ",
  "斜邊/對邊": "Hypotenuse over opposite",
  "斜邊/鄰邊": "Hypotenuse over adjacent",
  "兩個 x 坐標的乘積": "Product of the x-coordinates",
  "兩點的斜率": "Gradient of the line through the two points",
  "y 坐標之和": "Sum of the y-coordinates",
  "不需要刻度": "No scale is needed",
  "不需要表示": "Need not be represented",
  "只使用圖案": "Use symbols only",
  "省略資料來源": "Omit the data source",
  "誤導讀者": "Mislead readers",
  "只訪問朋友": "Survey friends only",
  "刪除不合意答案": "Delete unwanted answers",
  "只展示最高數值": "Show only the highest value",
  "結果必定準確": "Results are certainly accurate",
  "消除誤差": "Eliminate error",
  "增加樣本數目": "Increase the sample size",
  "樣本更多": "More samples",
  "平均數變大": "The mean increases",
  "數據必定錯誤": "The data must be incorrect",
  "圖表必定不美觀": "The chart must be unattractive",
  "柱形會消失": "The bars disappear",
  "資料會自動改變": "The data changes automatically",
  "顏色喜好": "Colour preference",
  "字體大小": "Font size",
  "頁碼": "Page number",
  "只標示 2": "Mark 2 only",
  "整條數線塗滿": "Shade the entire number line",
  "互補": "Supplementary",
  "直角": "Right angle",
  "平行": "Parallel",
  "垂直": "Perpendicular",
  "垂直線": "Vertical line",
  "斜線": "Sloping line",
  "曲線": "Curve",
  "東方": "East",
  "南方": "South",
  "西方": "West",
  "正東方向": "Due east",
  "正南方向": "Due south",
  "正西方向": "Due west",
  "中線": "Median",
  "高": "Altitude",
  "邊": "Side",
  "角平分線": "Angle bisector",
  "邊的垂直平分線": "Perpendicular bisector of a side",
  "原本金": "Original principal",
  "折扣額": "Discount amount",
  "虧損額": "Loss amount",
  "圖表顏色": "Chart colour",
  "中位數": "Median",
  "眾數": "Mode",
  "幾何平均數": "Geometric mean",
  "大於 1": "Greater than 1",
  "增加 3": "Increases by 3",
  "增加 1/3": "Increases by 1/3",
  "相乘為 −1": "Their product is −1",
  "相加為 0": "Their sum is 0",
  "底面半徑": "Base radius",
  "體積": "Volume",
  "球體表面積": "Surface area of a sphere",
  "有利結果 ÷ 所有理論結果": "Favourable outcomes ÷ all theoretical outcomes",
  "平均數 ÷ 眾數": "Mean ÷ mode",
});

export function localizeSecondaryOption(value: string, language: SecondaryLanguage) {
  const pair = value.split(" / ");
  if (pair.length === 2) return language === "zh" ? pair[0] : pair[1];
  return language === "en" ? englishChoices[value] ?? value : value;
}
