import { useMemo, useState } from "react";
import { Link } from "wouter";
import { Check, Clipboard, Cloud, GraduationCap, Link2, LogIn, ShieldCheck, UserRound, UsersRound, X } from "lucide-react";
import { toast } from "sonner";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import StudentProfileSyncPanel from "@/components/StudentProfileSyncPanel";

function Metric({ label, value, detail }: { label: string; value: string | number; detail: string }) {
  return <div className="rounded-2xl border border-[#172b3f]/12 bg-white p-4 shadow-[3px_3px_0_rgba(23,43,63,.05)]"><p className="font-mono text-[10px] font-bold tracking-[.12em] text-[#f05a3c]">{label}</p><strong className="mt-2 block text-3xl font-black">{value}</strong><small className="mt-1 block text-xs font-bold text-[#617286]">{detail}</small></div>;
}

export default function AccountHub() {
  const { user, loading, isAuthenticated, logout } = useAuth();
  const utils = trpc.useUtils();
  const [inviteCode, setInviteCode] = useState("");
  const overview = trpc.learning.overview.useQuery(undefined, { enabled: isAuthenticated });
  const grants = trpc.familyAccess.listMyGrants.useQuery(undefined, { enabled: isAuthenticated });
  const viewerStudents = trpc.familyAccess.viewerStudents.useQuery(undefined, { enabled: isAuthenticated });
  const createInvite = trpc.familyAccess.createInvite.useMutation({ onSuccess: () => { utils.familyAccess.listMyGrants.invalidate(); toast.success("邀請碼已建立，請安全地分享給指定人士。"); } });
  const revokeInvite = trpc.familyAccess.revokeInvite.useMutation({ onSuccess: () => { utils.familyAccess.listMyGrants.invalidate(); toast.success("授權已撤銷。"); } });
  const acceptInvite = trpc.familyAccess.acceptInvite.useMutation({ onSuccess: () => { utils.familyAccess.viewerStudents.invalidate(); setInviteCode(""); toast.success("已成功關聯學生帳戶。"); }, onError: (error) => toast.error(error.message) });
  const today = useMemo(() => new Date().toISOString().slice(0, 10), []);
  const todayPractices = overview.data?.dailyRecords.filter((record) => new Date(record.practicedOn).toISOString().slice(0, 10) === today).length ?? 0;

  if (loading) return <main className="grid min-h-screen place-items-center bg-[#f8f5ed] text-[#172b3f]"><p className="font-mono text-sm font-bold">正在讀取帳戶…</p></main>;
  if (!isAuthenticated) return <main className="grid min-h-screen place-items-center bg-[#f8f5ed] p-5 text-[#172b3f]"><section className="max-w-md rounded-[28px] border border-[#172b3f]/12 bg-white p-8 text-center shadow-[8px_8px_0_rgba(240,90,60,.12)]"><span className="mx-auto grid size-14 place-items-center rounded-2xl bg-[#f05a3c] text-white"><Cloud className="size-7" /></span><p className="mt-5 font-mono text-xs font-bold tracking-[.15em] text-[#f05a3c]">MATHS QUEST · ACCOUNT</p><h1 className="mt-3 text-3xl font-black">登入以備份你的學習地圖</h1><p className="mt-4 leading-7 text-[#617286]">完成星星、錯題、每日目標和釘選課題會安全同步到你的帳戶；未登入也可以繼續做練習。</p><Link href="/sign-in" className="mt-6 inline-flex items-center gap-2 rounded-xl bg-[#f05a3c] px-5 py-3 font-bold text-white"><LogIn className="size-4" /> 學生登入／註冊</Link><Link href="/" className="mt-5 block text-sm font-bold text-[#617286] hover:text-[#f05a3c]">返回首頁</Link></section></main>;

  return <main className="min-h-screen bg-[#f8f5ed] px-5 py-7 text-[#172b3f] sm:px-7"><div className="mx-auto max-w-6xl"><header className="flex flex-wrap items-start justify-between gap-5"><div><Link href="/" className="font-bold hover:text-[#f05a3c]">← 返回學習地圖</Link><p className="mt-7 font-mono text-[11px] font-bold tracking-[.15em] text-[#f05a3c]">ACCOUNT · CLOUD LEARNING</p><h1 className="mt-2 text-4xl font-black tracking-[-.05em]">{user?.name || "我的"}學習帳戶</h1><p className="mt-3 max-w-2xl leading-7 text-[#617286]">你的學習紀錄會在登入後持續備份；你可隨時建立、檢視或撤銷家長與教師的授權。</p></div><div className="flex items-center gap-3"><Link href="/family-dashboard" className="inline-flex items-center gap-2 rounded-xl border border-[#172b3f]/15 bg-white px-4 py-3 text-sm font-bold"><UsersRound className="size-4 text-[#0e8b87]" /> 家長／教師檢視</Link><button onClick={() => void logout()} className="rounded-xl border border-[#172b3f]/15 bg-white px-4 py-3 text-sm font-bold text-[#617286]">登出</button></div></header>

  <section className="mt-8 grid gap-4 sm:grid-cols-3"><Metric label="CLOUD STARS" value={overview.data?.progress.length ?? "—"} detail="已同步的完成課題" /><Metric label="TODAY" value={`${todayPractices}/${overview.data?.profile.dailyTarget ?? 3}`} detail="今日已備份練習" /><Metric label="REVIEW" value={overview.data?.reviewRecords.length ?? "—"} detail="等待補強的錯題站" /></section>

  <StudentProfileSyncPanel />

  <section className="mt-8 grid gap-6 lg:grid-cols-[1.15fr_.85fr]"><div className="rounded-[28px] border border-[#172b3f]/12 bg-white p-6 shadow-[7px_7px_0_rgba(23,43,63,.05)]"><div className="flex items-start justify-between gap-3"><div><p className="font-mono text-[10px] font-bold tracking-[.15em] text-[#0e8b87]">STUDENT PERMISSION</p><h2 className="mt-2 text-2xl font-black">授權家長或教師</h2><p className="mt-2 text-sm leading-6 text-[#617286]">建立一次性邀請碼後，只把它交給你信任的人；對方登入後才可接受並查看資料。</p></div><ShieldCheck className="size-8 text-[#0e8b87]" /></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><button disabled={createInvite.isPending} onClick={() => createInvite.mutate({ viewerRole: "parent" })} className="rounded-2xl border-2 border-[#f05a3c]/28 bg-[#fff7ef] p-4 text-left transition hover:-translate-y-0.5 disabled:opacity-60"><UserRound className="size-5 text-[#f05a3c]" /><strong className="mt-3 block">建立家長邀請碼</strong><small className="mt-1 block text-[#617286]">供家長查看你的進度與錯題</small></button><button disabled={createInvite.isPending} onClick={() => createInvite.mutate({ viewerRole: "teacher" })} className="rounded-2xl border-2 border-[#4f6eae]/28 bg-[#f3f7fd] p-4 text-left transition hover:-translate-y-0.5 disabled:opacity-60"><GraduationCap className="size-5 text-[#4f6eae]" /><strong className="mt-3 block">建立教師邀請碼</strong><small className="mt-1 block text-[#617286]">供教師查看學習與補強方向</small></button></div><div className="mt-6 space-y-3">{grants.data?.length ? grants.data.map(({ grant, viewerName, viewerEmail }) => <div key={grant.id} className="flex flex-wrap items-center gap-3 rounded-2xl border border-[#172b3f]/10 bg-[#fffdf8] p-4"><span className={`grid size-9 place-items-center rounded-xl ${grant.viewerRole === "parent" ? "bg-[#fff0e9] text-[#f05a3c]" : "bg-[#eef3ff] text-[#4f6eae]"}`}>{grant.viewerRole === "parent" ? <UserRound className="size-4" /> : <GraduationCap className="size-4" />}</span><div className="min-w-0 flex-1"><strong className="block text-sm">{grant.viewerRole === "parent" ? "家長" : "教師"} · {grant.status === "pending" ? "等待接受" : grant.status === "active" ? "已授權" : "已撤銷"}</strong><small className="block truncate text-[#617286]">{grant.status === "pending" ? grant.inviteCode : viewerName || viewerEmail || "已關聯帳戶"}</small></div>{grant.status === "pending" && <button onClick={() => { navigator.clipboard.writeText(grant.inviteCode); toast.success("邀請碼已複製。"); }} className="inline-flex items-center gap-1 rounded-lg border border-[#172b3f]/12 px-3 py-2 text-xs font-bold"><Clipboard className="size-3" /> 複製</button>}{grant.status !== "revoked" && <button disabled={revokeInvite.isPending} onClick={() => revokeInvite.mutate({ grantId: grant.id })} className="rounded-lg p-2 text-[#b84c36] hover:bg-[#fff0e9]" aria-label="撤銷授權"><X className="size-4" /></button>}</div>) : <p className="rounded-2xl border border-dashed border-[#172b3f]/15 p-5 text-sm text-[#617286]">尚未建立任何授權。你可按上方按鈕產生一組安全邀請碼。</p>}</div></div>

  <div className="space-y-6"><section className="rounded-[28px] border border-[#172b3f]/12 bg-[#172b3f] p-6 text-white"><p className="font-mono text-[10px] font-bold tracking-[.15em] text-[#f6be5d]">VIEWER LINK</p><h2 className="mt-2 text-2xl font-black">我是家長或教師</h2><p className="mt-2 text-sm leading-6 text-white/70">輸入學生親自交給你的邀請碼；未經學生同意，不可看到任何學習資料。</p><label className="mt-5 block font-mono text-[10px] font-bold tracking-[.12em] text-white/70">INVITE CODE</label><input value={inviteCode} onChange={(event) => setInviteCode(event.target.value.toUpperCase())} placeholder="MQ-XXXXXXXXXX" className="mt-2 w-full rounded-xl border border-white/20 bg-white/10 px-4 py-3 font-mono font-bold text-white placeholder:text-white/35" /><button disabled={!inviteCode || acceptInvite.isPending} onClick={() => acceptInvite.mutate({ inviteCode })} className="mt-3 inline-flex items-center gap-2 rounded-xl bg-[#f05a3c] px-4 py-3 text-sm font-bold disabled:opacity-50"><Link2 className="size-4" /> 接受授權並關聯</button></section><section className="rounded-[28px] border border-[#172b3f]/12 bg-white p-6"><div className="flex items-center justify-between"><div><p className="font-mono text-[10px] font-bold tracking-[.15em] text-[#4f6eae]">VIEWER DASHBOARD</p><h2 className="mt-2 text-xl font-black">已關聯的學生</h2></div><UsersRound className="size-6 text-[#4f6eae]" /></div>{viewerStudents.data?.length ? <><p className="mt-4 text-sm text-[#617286]">你已獲授權查看 {viewerStudents.data.length} 位學生。</p><Link href="/family-dashboard" className="mt-4 inline-flex items-center gap-2 rounded-xl border border-[#4f6eae]/30 bg-[#f3f7fd] px-4 py-3 text-sm font-bold text-[#36598f]">開啟專屬檢視 <Check className="size-4" /></Link></> : <p className="mt-4 text-sm leading-6 text-[#617286]">輸入學生的邀請碼後，授權學生會顯示在這裡。</p>}</section></div></section></div></main>;
}
