import { useEffect, useMemo, useState } from "react";
import { Link } from "wouter";
import { BookOpen, Cloud, GraduationCap, ShieldCheck, Target, UsersRound } from "lucide-react";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";

export default function FamilyDashboard() {
  const { isAuthenticated, loading } = useAuth();
  const [studentId, setStudentId] = useState<number | null>(null);
  const students = trpc.familyAccess.viewerStudents.useQuery(undefined, { enabled: isAuthenticated });
  useEffect(() => { if (!studentId && students.data?.[0]) setStudentId(students.data[0].studentId); }, [studentId, students.data]);
  const studentInput = useMemo(() => ({ studentId: studentId ?? 0 }), [studentId]);
  const overview = trpc.familyAccess.viewerStudentOverview.useQuery(studentInput, { enabled: Boolean(studentId) });
  const selected = students.data?.find((student) => student.studentId === studentId);
  const today = new Date().toISOString().slice(0, 10);
  const todayCount = overview.data?.dailyRecords.filter((record) => new Date(record.practicedOn).toISOString().slice(0, 10) === today).length ?? 0;

  if (loading) return <main className="grid min-h-screen place-items-center bg-[#f8f5ed] font-mono font-bold text-[#172b3f]">正在驗證授權…</main>;
  if (!isAuthenticated) return <main className="grid min-h-screen place-items-center bg-[#f8f5ed] p-5 text-center text-[#172b3f]"><section className="max-w-md rounded-3xl bg-white p-8 shadow-[7px_7px_0_rgba(23,43,63,.08)]"><ShieldCheck className="mx-auto size-10 text-[#0e8b87]" /><h1 className="mt-4 text-3xl font-black">需要登入與學生授權</h1><p className="mt-3 text-[#617286]">請先登入，然後在帳戶頁輸入學生親自提供的邀請碼。</p><Link href="/account" className="mt-5 inline-block rounded-xl bg-[#f05a3c] px-5 py-3 font-bold text-white">前往帳戶</Link></section></main>;

  return <main className="min-h-screen bg-[#f8f5ed] px-5 py-7 text-[#172b3f] sm:px-7"><div className="mx-auto max-w-6xl"><header><Link href="/account" className="font-bold hover:text-[#f05a3c]">← 返回帳戶</Link><p className="mt-7 font-mono text-[11px] font-bold tracking-[.15em] text-[#4f6eae]">AUTHORISED VIEW · FAMILY & TEACHER</p><h1 className="mt-2 text-4xl font-black tracking-[-.05em]">學生學習檢視</h1><p className="mt-3 max-w-2xl leading-7 text-[#617286]">僅顯示已由學生主動授權的進度、每日目標與補強重點。學生可隨時在帳戶頁撤銷授權。</p></header>
  <section className="mt-7 grid gap-6 lg:grid-cols-[260px_1fr]"><aside className="rounded-[26px] border border-[#172b3f]/12 bg-white p-4"><p className="px-2 font-mono text-[10px] font-bold tracking-[.14em] text-[#4f6eae]">MY STUDENTS</p><div className="mt-3 grid gap-2">{students.data?.length ? students.data.map((student) => <button key={student.studentId} onClick={() => setStudentId(student.studentId)} className={`rounded-xl p-3 text-left transition ${student.studentId === studentId ? "bg-[#eef3ff] text-[#36598f]" : "hover:bg-[#f8f5ed]"}`}><strong className="block">{student.studentName || student.studentUserName || "學生帳戶"}</strong><small className="mt-1 block text-xs text-[#617286]">{student.viewerRole === "parent" ? "家長授權" : "教師授權"} · 每日 {student.dailyTarget} 題</small></button>) : <p className="p-3 text-sm leading-6 text-[#617286]">尚未有已關聯學生。請於帳戶頁輸入學生邀請碼。</p>}</div></aside>
  <section>{selected && overview.data ? <><div className="rounded-[28px] bg-[#172b3f] p-6 text-white"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2 text-[#f6be5d]"><GraduationCap className="size-4" /><span className="font-mono text-[10px] font-bold tracking-[.14em]">AUTHORISED STUDENT</span></div><h2 className="mt-3 text-3xl font-black">{selected.studentName || selected.studentUserName || "學生"}</h2><p className="mt-2 text-sm text-white/70">授權角色：{selected.viewerRole === "parent" ? "家長" : "教師"}。請以鼓勵與共同訂立目標為主。</p></div><ShieldCheck className="size-9 text-[#80d8cf]" /></div></div><div className="mt-5 grid gap-4 sm:grid-cols-3"><div className="rounded-2xl border border-[#172b3f]/12 bg-white p-5"><BookOpen className="size-5 text-[#f05a3c]" /><strong className="mt-3 block text-3xl font-black">{overview.data.progress.length}</strong><small className="text-[#617286]">已完成並備份課題</small></div><div className="rounded-2xl border border-[#172b3f]/12 bg-white p-5"><Target className="size-5 text-[#0e8b87]" /><strong className="mt-3 block text-3xl font-black">{todayCount}/{overview.data.profile.dailyTarget}</strong><small className="text-[#617286]">今日練習目標</small></div><div className="rounded-2xl border border-[#172b3f]/12 bg-white p-5"><Cloud className="size-5 text-[#4f6eae]" /><strong className="mt-3 block text-3xl font-black">{overview.data.reviewRecords.length}</strong><small className="text-[#617286]">補強中的錯題站</small></div></div><section className="mt-5 rounded-[28px] border border-[#172b3f]/12 bg-white p-6"><div className="flex items-center gap-2"><UsersRound className="size-5 text-[#f05a3c]" /><h3 className="text-xl font-black">建議一起查看的補強重點</h3></div>{overview.data.reviewRecords.length ? <div className="mt-4 grid gap-3 sm:grid-cols-2">{overview.data.reviewRecords.slice(0, 6).map((record) => <div key={record.id} className="rounded-2xl bg-[#fff7ef] p-4"><p className="font-mono text-[10px] font-bold tracking-[.12em] text-[#f05a3c]">{record.grade} · REVIEW</p><strong className="mt-2 block">{record.title}</strong><small className="mt-2 block text-[#617286]">需要重溫 {record.misses} 次 · 最近更新 {new Date(record.updatedAt).toLocaleDateString("zh-HK")}</small></div>)}</div> : <p className="mt-4 rounded-2xl border border-dashed border-[#172b3f]/15 p-5 text-[#617286]">暫時沒有雲端錯題紀錄。學生完成練習後，這裡會顯示建議補強課題。</p>}</section></> : <div className="rounded-[28px] border border-dashed border-[#172b3f]/15 bg-white p-8 text-center text-[#617286]">選擇一位已授權學生以查看學習概況。</div>}</section></section></div></main>;
}
