import { useState } from "react";
import { Link } from "wouter";
import { Check, RotateCcw, Trophy, X } from "lucide-react";
import { markPracticeCompleted } from "@/lib/practiceCompletion";
import { recordDailyPractice } from "@/lib/dailyPractice";
import { recordPracticeMistake } from "@/lib/reviewRecommendations";

const areas = [{ shape: "平行四邊形", detail: "底 8 厘米，高 5 厘米", answer: 40, hint: "平行四邊形面積 = 底 × 高。" }, { shape: "三角形", detail: "底 10 厘米，高 6 厘米", answer: 30, hint: "三角形面積 = 底 × 高 ÷ 2。" }, { shape: "梯形", detail: "上底 4 厘米，下底 8 厘米，高 5 厘米", answer: 30, hint: "梯形面積 =（上底 + 下底）× 高 ÷ 2。" }, { shape: "平行四邊形", detail: "底 12 厘米，高 3 厘米", answer: 36, hint: "平行四邊形面積 = 底 × 高。" }, { shape: "三角形", detail: "底 14 厘米，高 4 厘米", answer: 28, hint: "三角形面積 = 底 × 高 ÷ 2。" }, { shape: "梯形", detail: "上底 6 厘米，下底 10 厘米，高 4 厘米", answer: 32, hint: "梯形面積 =（上底 + 下底）× 高 ÷ 2。" }, { shape: "三角形", detail: "底 9 厘米，高 8 厘米", answer: 36, hint: "三角形面積 = 底 × 高 ÷ 2。" }, { shape: "平行四邊形", detail: "底 7 厘米，高 9 厘米", answer: 63, hint: "平行四邊形面積 = 底 × 高。" }];
const volumes = [{ item: "水箱", detail: "長 2 公尺、闊 1 公尺、高 1.5 公尺", answer: 3, unit: "立方公尺" }, { item: "包裝箱", detail: "長 40 厘米、闊 30 厘米、高 20 厘米", answer: 24000, unit: "立方厘米" }, { item: "水箱", detail: "長 3 公尺、闊 2 公尺、高 1 公尺", answer: 6, unit: "立方公尺" }, { item: "包裝箱", detail: "長 50 厘米、闊 20 厘米、高 10 厘米", answer: 10000, unit: "立方厘米" }, { item: "魚缸", detail: "長 80 厘米、闊 30 厘米、高 40 厘米", answer: 96000, unit: "立方厘米" }, { item: "包裝箱", detail: "長 25 厘米、闊 20 厘米、高 20 厘米", answer: 10000, unit: "立方厘米" }, { item: "水箱", detail: "長 4 公尺、闊 1 公尺、高 2 公尺", answer: 8, unit: "立方公尺" }, { item: "儲物箱", detail: "長 60 厘米、闊 40 厘米、高 30 厘米", answer: 72000, unit: "立方厘米" }];
type Result = "idle" | "correct" | "incorrect";
const choicesFor = (answer: number) => Array.from(new Set([answer, answer + 2, Math.max(1, answer - 2), answer + 4]));

export default function P5AppliedPractice() {
  const isArea = location.pathname.includes("area-puzzle"); const [index, setIndex] = useState(0); const [placed, setPlaced] = useState(false); const [result, setResult] = useState<Result>("idle"); const [finished, setFinished] = useState(false); const [mistakes, setMistakes] = useState<number[]>([]); const areaQuestion = areas[index]; const volumeQuestion = volumes[index]; const answer = isArea ? areaQuestion.answer : volumeQuestion.answer; const unit = isArea ? "平方厘米" : volumeQuestion.unit;
  const choose = (value: number) => { if (result !== "idle") return; if (value === answer && (!isArea || placed)) { setResult("correct"); return; } setResult("incorrect"); setMistakes((items) => items.includes(index) ? items : [...items, index]); recordPracticeMistake({ key: isArea ? "p5-area-puzzle" : "p5-volume-life", grade: "P5", title: isArea ? "面積公式拼圖" : "體積生活題", href: location.pathname }); };
  const next = () => { if (index === 7) { const key = isArea ? "p5-area-puzzle" : "p5-volume-life"; markPracticeCompleted(key); recordDailyPractice(key); setFinished(true); return; } setIndex((value) => value + 1); setPlaced(false); setResult("idle"); };
  if (finished) return <main className="grid min-h-screen place-items-center bg-[#f8f5ed] p-6 text-[#172b3f]"><section className="max-w-lg rounded-[30px] border bg-white p-8 text-center"><Trophy className="mx-auto size-14 text-[#c8811e]" /><h1 className="mt-4 text-3xl font-black">完成八題挑戰！</h1><p className="mt-3 text-[#617286]">你已完成 {isArea ? "面積公式拼圖" : "體積生活題"}。</p><div className="mt-6 flex flex-wrap justify-center gap-3">{mistakes.length > 0 && <button onClick={() => { setFinished(false); setIndex(mistakes[0]); setResult("idle"); }} className="rounded-xl border border-[#f05a3c]/30 px-4 py-3 font-bold text-[#b84c36]">重溫 {mistakes.length} 題錯題</button>}<button onClick={() => { setIndex(0); setPlaced(false); setResult("idle"); setFinished(false); setMistakes([]); }} className="rounded-xl border px-4 py-3 font-bold"><RotateCcw className="mr-1 inline size-4" />再玩一次</button><Link href="/#path" className="rounded-xl bg-[#f05a3c] px-4 py-3 font-bold text-white">返回題目庫</Link></div></section></main>;
  return <main className="min-h-screen bg-[#f8f5ed] p-6 text-[#172b3f]"><div className="mx-auto max-w-3xl"><Link href="/#path" className="font-bold hover:text-[#f05a3c]">← 返回題目庫</Link><header className="mt-7 flex items-end justify-between gap-3"><div><p className="font-mono text-xs font-bold tracking-[.14em] text-[#6c8b4c]">P5 · {isArea ? "面積公式" : "體積應用"}</p><h1 className="mt-2 text-4xl font-black">{isArea ? "面積公式拼圖推導" : "體積生活應用"}</h1></div><p className="rounded-full border bg-white px-4 py-2 font-mono font-bold">第 {index + 1} / 8 題</p></header><section className="mq-practice-card mt-6 rounded-3xl border bg-white p-8 text-center">{isArea ? <><h2 className="mt-4 text-2xl font-black">{areaQuestion.shape}：{areaQuestion.detail}</h2><button draggable onDragStart={(event) => event.dataTransfer.setData("text/plain", "piece")} onClick={() => setPlaced(true)} className={`mx-auto mt-6 grid h-32 w-52 place-items-center border-4 border-dashed ${placed ? "border-[#0e8b87] bg-[#e8f5f2]" : "border-[#f05a3c] bg-[#fff0e9]"}`}>點選或拖曳碎片完成拼圖</button><p className="mx-auto mt-4 max-w-md rounded-xl bg-[#eff6e9] p-3 text-sm">{placed ? `已完成拼圖。${areaQuestion.hint}` : "先完成拼圖，才可選擇答案。"}</p></> : <><h2 className="mt-4 text-2xl font-black">{volumeQuestion.item}：{volumeQuestion.detail}</h2><div className="mx-auto mt-6 grid w-52 grid-cols-3 gap-1" style={{ transform: "skewY(-8deg)" }}>{Array.from({ length: 9 }, (_, item) => <i key={item} className="aspect-square border border-[#172b3f] bg-[#4f6eae]" />)}</div><p className="mx-auto mt-4 max-w-md rounded-xl bg-[#eef5ff] p-3 text-sm">體積 = 長 × 闊 × 高；答案要用{unit}。</p></>}<p className="mt-5 text-lg font-bold">答案是多少{unit}？</p><div className="mq-concept-choices mx-auto mt-5">{choicesFor(answer).map((value) => <button key={value} onClick={() => choose(value)} disabled={result !== "idle"}>{value.toLocaleString()} {unit}</button>)}</div>{result !== "idle" && <div className={`mx-auto mt-6 max-w-xl rounded-2xl border p-4 font-bold ${result === "correct" ? "border-[#0e8b87]/25 bg-[#e8f5f2] text-[#135d59]" : "border-[#f05a3c]/25 bg-[#fff0e9] text-[#8c3f2e]"}`}>{result === "correct" ? <Check className="mr-2 inline size-5" /> : <X className="mr-2 inline size-5" />}{result === "correct" ? "答對了！" : isArea && !placed ? "請先點選或拖曳碎片完成拼圖。" : `再試一次。${isArea ? areaQuestion.hint : "體積 = 長 × 闊 × 高。"}`}</div>}<div className="mt-6">{result === "correct" ? <button className="mq-start rounded-xl bg-[#f05a3c] px-5 py-3 text-white" onClick={next}>{index === 7 ? "完成挑戰" : "下一題"}</button> : result === "incorrect" ? <button className="mq-start rounded-xl bg-[#f05a3c] px-5 py-3 text-white" onClick={() => setResult("idle")}><RotateCcw className="mr-1 inline size-4" />再試一次</button> : null}</div></section></div></main>;
}
