import { useState } from "react";
import { Link } from "wouter";
import { Check, RotateCcw, Trophy, Volume2, X } from "lucide-react";
import { markPracticeCompleted } from "@/lib/practiceCompletion";
import { recordDailyPractice } from "@/lib/dailyPractice";
import { recordPracticeMistake } from "@/lib/reviewRecommendations";
import { speakCantonese, speakCorrectEncouragement, speakTryAgain } from "@/lib/speech";

type Question = { prompt: string; answer: string; choices: string[]; hint: string; equation?: string; data?: number[] };
const units: Question[] = [
  { prompt: "1 立方公尺等於多少立方厘米？", answer: "1,000,000 立方厘米", choices: ["1,000,000 立方厘米", "100,000 立方厘米", "10,000 立方厘米", "1,000 立方厘米"], hint: "1 公尺 = 100 厘米，所以 1 立方公尺 = 100 × 100 × 100 立方厘米。" },
  { prompt: "2 立方公尺等於多少立方厘米？", answer: "2,000,000 立方厘米", choices: ["2,000,000 立方厘米", "200,000 立方厘米", "20,000 立方厘米", "2,000 立方厘米"], hint: "先把 1 立方公尺換成 1,000,000 立方厘米，再乘 2。" },
  { prompt: "500,000 立方厘米等於多少立方公尺？", answer: "0.5 立方公尺", choices: ["0.5 立方公尺", "5 立方公尺", "0.05 立方公尺", "500 立方公尺"], hint: "以 1,000,000 立方厘米為 1 立方公尺。" },
  { prompt: "3,000,000 立方厘米等於多少立方公尺？", answer: "3 立方公尺", choices: ["3 立方公尺", "30 立方公尺", "0.3 立方公尺", "300 立方公尺"], hint: "3,000,000 ÷ 1,000,000 = 3。" },
  { prompt: "0.2 立方公尺等於多少立方厘米？", answer: "200,000 立方厘米", choices: ["200,000 立方厘米", "20,000 立方厘米", "2,000,000 立方厘米", "200 立方厘米"], hint: "0.2 × 1,000,000 = 200,000。" },
  { prompt: "1,500,000 立方厘米等於多少立方公尺？", answer: "1.5 立方公尺", choices: ["1.5 立方公尺", "15 立方公尺", "0.15 立方公尺", "150 立方公尺"], hint: "1,500,000 ÷ 1,000,000 = 1.5。" },
  { prompt: "4 立方公尺等於多少立方厘米？", answer: "4,000,000 立方厘米", choices: ["4,000,000 立方厘米", "400,000 立方厘米", "40,000 立方厘米", "4,000 立方厘米"], hint: "每 1 立方公尺是 1,000,000 立方厘米。" },
  { prompt: "750,000 立方厘米等於多少立方公尺？", answer: "0.75 立方公尺", choices: ["0.75 立方公尺", "7.5 立方公尺", "0.075 立方公尺", "75 立方公尺"], hint: "750,000 ÷ 1,000,000 = 0.75。" },
];
const carry: Question[] = [
  { equation: "4.78\n＋ 2.65", prompt: "計算 4.78 ＋ 2.65。", answer: "7.43", choices: ["7.43", "6.43", "7.33", "7.53"], hint: "百分位 8 + 5 = 13，寫 3，向十分位進 1。" }, { equation: "9.20\n－ 3.75", prompt: "計算 9.20 － 3.75。", answer: "5.45", choices: ["5.45", "6.55", "5.55", "6.45"], hint: "十分位 2 不夠減 7，向個位借 1 個，變成 12 個十分位。" },
  { equation: "6.39\n＋ 1.87", prompt: "計算 6.39 ＋ 1.87。", answer: "8.26", choices: ["8.26", "7.26", "8.16", "8.36"], hint: "百分位 9 + 7 = 16，寫 6，向十分位進 1。" }, { equation: "8.00\n－ 2.46", prompt: "計算 8.00 － 2.46。", answer: "5.54", choices: ["5.54", "6.54", "5.64", "6.46"], hint: "0 不夠減 6，要逐欄向左借位。" },
  { equation: "5.67\n＋ 3.58", prompt: "計算 5.67 ＋ 3.58。", answer: "9.25", choices: ["9.25", "8.25", "9.15", "9.35"], hint: "百分位 7 + 8 = 15，進 1 到十分位。" }, { equation: "7.30\n－ 1.85", prompt: "計算 7.30 － 1.85。", answer: "5.45", choices: ["5.45", "6.55", "5.55", "6.45"], hint: "十分位 3 不夠減 8，先向個位借 1。" },
  { equation: "2.49\n＋ 4.62", prompt: "計算 2.49 ＋ 4.62。", answer: "7.11", choices: ["7.11", "6.11", "7.01", "7.21"], hint: "百分位 9 + 2 = 11，寫 1，向十分位進 1。" }, { equation: "10.00\n－ 6.48", prompt: "計算 10.00 － 6.48。", answer: "3.52", choices: ["3.52", "4.52", "3.62", "4.48"], hint: "0 不夠減 8，從左邊的 1 逐欄借位。" },
];
const polygons: Question[] = [
  { prompt: "五邊形有多少條邊？", answer: "5 條邊", choices: ["5 條邊", "4 條邊", "6 條邊", "8 條邊"], hint: "沿外框逐邊點數。" }, { prompt: "六邊形有多少條邊？", answer: "6 條邊", choices: ["6 條邊", "5 條邊", "7 條邊", "8 條邊"], hint: "每一條直邊數一次。" },
  { prompt: "八邊形有多少條邊？", answer: "8 條邊", choices: ["8 條邊", "6 條邊", "7 條邊", "10 條邊"], hint: "像停止標誌的外框。" }, { prompt: "正五邊形有幾條對稱軸？", answer: "5 條對稱軸", choices: ["5 條對稱軸", "4 條對稱軸", "6 條對稱軸", "8 條對稱軸"], hint: "每個頂點可對準對面的邊中點。" },
  { prompt: "正六邊形旋轉多少度後會第一次重合？", answer: "60°", choices: ["60°", "90°", "120°", "180°"], hint: "一整圈 360° 平均分成 6 份。" }, { prompt: "正方形旋轉多少度後會第一次重合？", answer: "90°", choices: ["90°", "60°", "120°", "180°"], hint: "一整圈 360° 平均分成 4 份。" },
  { prompt: "正三角形有幾條對稱軸？", answer: "3 條對稱軸", choices: ["3 條對稱軸", "2 條對稱軸", "4 條對稱軸", "6 條對稱軸"], hint: "每個頂點都有一條折線。" }, { prompt: "七邊形有多少條邊？", answer: "7 條邊", choices: ["7 條邊", "5 條邊", "6 條邊", "8 條邊"], hint: "沿外框逐邊點數。" },
];
const data: Question[] = [
  { data: [4, 6, 8, 10], prompt: "下列四日數據的平均數是多少？", answer: "7", choices: ["7", "6", "8", "9"], hint: "總和 28 ÷ 4 = 7。" }, { data: [3, 5, 7, 9, 11], prompt: "下列五日數據的平均數是多少？", answer: "7", choices: ["7", "6", "8", "9"], hint: "總和 35 ÷ 5 = 7。" },
  { data: [2, 6, 4, 8], prompt: "下列四日數據中，最高數值是多少？", answer: "8", choices: ["8", "6", "4", "2"], hint: "找最高的柱或點。" }, { data: [9, 7, 5, 3], prompt: "這組四日數據的整體趨勢是甚麼？", answer: "下降", choices: ["下降", "上升", "保持不變", "無法判斷"], hint: "每一天都比前一天低。" },
  { data: [4, 4, 6, 6], prompt: "下列四日數據的平均數是多少？", answer: "5", choices: ["5", "4", "6", "8"], hint: "總和 20 ÷ 4 = 5。" }, { data: [5, 8, 6, 9], prompt: "下列四日數據中，最低數值是多少？", answer: "5", choices: ["5", "6", "8", "9"], hint: "找最靠近橫軸的數值。" },
  { data: [1, 3, 5, 7, 9], prompt: "下列五日數據的平均數是多少？", answer: "5", choices: ["5", "4", "6", "7"], hint: "總和 25 ÷ 5 = 5。" }, { data: [2, 5, 5, 8], prompt: "這組四日數據的整體趨勢是甚麼？", answer: "上升", choices: ["上升", "下降", "保持不變", "無法判斷"], hint: "最後一天比第一天高。" },
];
type Result = "idle" | "correct" | "incorrect";

export default function P5ExpansionPractice() {
  const path = location.pathname; const kind = path.includes("volume-units") ? "unit" : path.includes("decimal-carry") ? "carry" : path.includes("polygons") ? "shape" : "data";
  const bank = kind === "unit" ? units : kind === "carry" ? carry : kind === "shape" ? polygons : data;
  const config = kind === "unit" ? { key: "p5-volume-units", title: "體積單位換算", code: "UNIT" } : kind === "carry" ? { key: "p5-decimal-carry", title: "小數進位與借位", code: "DEC+" } : kind === "shape" ? { key: "p5-polygons", title: "多邊形、旋轉與軸對稱", code: "SHAPE" } : { key: "p5-data-insights", title: "平均數與折線圖判讀", code: "DATA+" };
  const [index, setIndex] = useState(0); const [result, setResult] = useState<Result>("idle"); const [finished, setFinished] = useState(false); const [mistakes, setMistakes] = useState<number[]>([]); const question = bank[index];
  const choose = (value: string) => { if (result !== "idle") return; if (value === question.answer) { setResult("correct"); speakCorrectEncouragement(); return; } setResult("incorrect"); setMistakes((items) => items.includes(index) ? items : [...items, index]); speakTryAgain(); recordPracticeMistake({ key: config.key, grade: "P5", title: config.title, href: location.pathname }); };
  const next = () => { if (index === 7) { markPracticeCompleted(config.key); recordDailyPractice(config.key); setFinished(true); speakCantonese("你完成了八題挑戰！"); return; } setIndex((value) => value + 1); setResult("idle"); };
  const restart = () => { setIndex(0); setResult("idle"); setFinished(false); setMistakes([]); };
  if (finished) return <main className="grid min-h-screen place-items-center bg-[#f8f5ed] p-6 text-[#172b3f]"><section className="max-w-lg rounded-[30px] border bg-white p-8 text-center"><Trophy className="mx-auto size-14 text-[#c8811e]" /><h1 className="mt-4 text-3xl font-black">完成八題挑戰！</h1><p className="mt-3 text-[#617286]">你已完成「{config.title}」。</p><div className="mt-6 flex flex-wrap justify-center gap-3">{mistakes.length > 0 && <button onClick={() => { setFinished(false); setIndex(mistakes[0]); setResult("idle"); }} className="rounded-xl border border-[#f05a3c]/30 px-4 py-3 font-bold text-[#b84c36]">重溫 {mistakes.length} 題錯題</button>}<button onClick={restart} className="rounded-xl border px-4 py-3 font-bold"><RotateCcw className="mr-1 inline size-4" />再玩一次</button><Link href="/#path" className="rounded-xl bg-[#f05a3c] px-4 py-3 font-bold text-white">返回題目庫</Link></div></section></main>;
  return <main className="min-h-screen bg-[#f8f5ed] p-6 text-[#172b3f]"><div className="mx-auto max-w-3xl"><Link href="/#path" className="font-bold hover:text-[#f05a3c]">← 返回題目庫</Link><header className="mt-7 flex items-end justify-between gap-3"><div><p className="font-mono text-xs font-bold tracking-[.14em] text-[#6c8b4c]">P5 · {config.code}</p><h1 className="mt-2 text-4xl font-black">{config.title}</h1></div><p className="rounded-full border bg-white px-4 py-2 font-mono font-bold">第 {index + 1} / 8 題</p></header><section className="mq-practice-card mt-6 rounded-3xl border bg-white p-8 text-center"><div className="flex justify-end"><button onClick={() => speakCantonese(question.prompt)} className="inline-flex items-center gap-1 rounded-full border px-3 py-2 text-xs font-bold"><Volume2 className="size-3" /> 聽題目</button></div>{kind === "carry" && <pre className="mx-auto mt-6 w-60 border-b-2 border-[#172b3f] pb-2 text-right font-mono text-3xl font-black">{question.equation}</pre>}{kind === "shape" && <div className="mx-auto mt-6 grid size-28 place-items-center border-4 border-dashed border-[#6c8b4c] text-5xl">⬠</div>}{kind === "data" && <div className="mx-auto mt-6 flex h-32 max-w-sm items-end justify-around border-b-2 border-l-2 px-5">{question.data?.map((value, position) => <i key={position} className="w-7 bg-[#6c8b4c]" style={{ height: `${value * 10}px` }} />)}</div>}<h2 className="mx-auto mt-6 max-w-xl text-2xl font-black">{question.prompt}</h2><p className="mx-auto mt-4 max-w-xl rounded-xl bg-[#eff6e9] p-3 text-sm">提示：{question.hint}</p><div className="mq-concept-choices mx-auto mt-7">{question.choices.map((choice) => <button key={choice} onClick={() => choose(choice)} disabled={result !== "idle"}>{choice}</button>)}</div>{result !== "idle" && <div className={`mx-auto mt-6 max-w-xl rounded-2xl border p-4 font-bold ${result === "correct" ? "border-[#0e8b87]/25 bg-[#e8f5f2] text-[#135d59]" : "border-[#f05a3c]/25 bg-[#fff0e9] text-[#8c3f2e]"}`}>{result === "correct" ? <Check className="mr-2 inline size-5" /> : <X className="mr-2 inline size-5" />}{result === "correct" ? "答對了！" : `再試一次。${question.hint}`}</div>}<div className="mt-6">{result === "correct" ? <button className="mq-start rounded-xl bg-[#f05a3c] px-5 py-3 text-white" onClick={next}>{index === 7 ? "完成挑戰" : "下一題"}</button> : result === "incorrect" ? <button className="mq-start rounded-xl bg-[#f05a3c] px-5 py-3 text-white" onClick={() => setResult("idle")}><RotateCcw className="mr-1 inline size-4" />再試一次</button> : null}</div></section></div></main>;
}
