import { useState } from "react";
import { Link } from "wouter";
import { Check, RotateCcw, Trophy, Volume2, X } from "lucide-react";
import { markPracticeCompleted } from "@/lib/practiceCompletion";
import { recordDailyPractice } from "@/lib/dailyPractice";
import { recordPracticeMistake } from "@/lib/reviewRecommendations";
import { speakCantonese, speakCorrectEncouragement, speakTryAgain } from "@/lib/speech";

const questions = [
  { a: "1/2", op: "×", b: "3/4", answer: "3/8", choices: ["3/8", "3/4", "1/2", "5/8"] }, { a: "2/3", op: "×", b: "3/4", answer: "1/2", choices: ["1/2", "5/7", "2/4", "3/7"] },
  { a: "3/4", op: "×", b: "2/3", answer: "1/2", choices: ["1/2", "5/7", "3/6", "2/7"] }, { a: "1/2", op: "÷", b: "1/4", answer: "2", choices: ["2", "1/8", "3/4", "1/2"] },
  { a: "3/4", op: "÷", b: "1/2", answer: "3/2", choices: ["3/2", "3/8", "2/3", "1/2"] }, { a: "2/5", op: "÷", b: "1/5", answer: "2", choices: ["2", "2/25", "1/2", "1/5"] },
  { a: "1/3", op: "×", b: "3/5", answer: "1/5", choices: ["1/5", "3/8", "4/5", "1/8"] }, { a: "4/5", op: "×", b: "2/5", answer: "8/25", choices: ["8/25", "6/10", "8/10", "2/25"] },
];
type Result = "idle" | "correct" | "incorrect";
const Fraction = ({ value }: { value: string }) => value.includes("/") ? <span className="inline-flex flex-col align-middle leading-none"><b className="border-b-2 px-1">{value.split("/")[0]}</b><b className="px-1">{value.split("/")[1]}</b></span> : <span>{value}</span>;

export default function P5FractionVisualPractice() {
  const [index, setIndex] = useState(0); const [result, setResult] = useState<Result>("idle"); const [finished, setFinished] = useState(false); const [mistakes, setMistakes] = useState<number[]>([]);
  const question = questions[index]; const prompt = `計算 ${question.a} ${question.op} ${question.b}，並把答案約成最簡分數。`;
  const choose = (value: string) => { if (result !== "idle") return; if (value === question.answer) { setResult("correct"); speakCorrectEncouragement(); return; } setResult("incorrect"); setMistakes((items) => items.includes(index) ? items : [...items, index]); speakTryAgain(); recordPracticeMistake({ key: "p5-fraction-visual", grade: "P5", title: "分數乘除圖形模型", href: "/practice/p5-fraction-visual" }); };
  const next = () => { if (index === 7) { markPracticeCompleted("p5-fraction-visual"); recordDailyPractice("p5-fraction-visual"); setFinished(true); speakCantonese("你完成了八題分數挑戰！"); return; } setIndex((value) => value + 1); setResult("idle"); };
  const restart = () => { setIndex(0); setResult("idle"); setFinished(false); setMistakes([]); };
  if (finished) return <main className="grid min-h-screen place-items-center bg-[#f8f5ed] p-6 text-[#172b3f]"><section className="max-w-lg rounded-[30px] border bg-white p-8 text-center"><Trophy className="mx-auto size-14 text-[#c8811e]" /><h1 className="mt-4 text-3xl font-black">完成八題分數挑戰！</h1><p className="mt-3 text-[#617286]">你已完成分數乘除圖形模型站。</p><div className="mt-6 flex flex-wrap justify-center gap-3">{mistakes.length > 0 && <button onClick={() => { setFinished(false); setIndex(mistakes[0]); setResult("idle"); }} className="rounded-xl border border-[#f05a3c]/30 px-4 py-3 font-bold text-[#b84c36]">重溫 {mistakes.length} 題錯題</button>}<button onClick={restart} className="rounded-xl border px-4 py-3 font-bold"><RotateCcw className="mr-1 inline size-4" />再玩一次</button><Link href="/#path" className="rounded-xl bg-[#f05a3c] px-4 py-3 font-bold text-white">返回題目庫</Link></div></section></main>;
  return <main className="min-h-screen bg-[#f8f5ed] p-6 text-[#172b3f]"><div className="mx-auto max-w-3xl"><Link href="/#path" className="font-bold hover:text-[#f05a3c]">← 返回題目庫</Link><header className="mt-7 flex items-end justify-between gap-3"><div><p className="font-mono text-xs font-bold tracking-[.14em] text-[#b85b7d]">P5 · 分數乘法與除法</p><h1 className="mt-2 text-4xl font-black">分數乘除圖形模型</h1></div><p className="rounded-full border bg-white px-4 py-2 font-mono font-bold">第 {index + 1} / 8 題</p></header><section className="mq-practice-card mt-6 rounded-3xl border bg-white p-8 text-center"><div className="flex justify-end"><button onClick={() => speakCantonese(prompt)} className="inline-flex items-center gap-1 rounded-full border px-3 py-2 text-xs font-bold"><Volume2 className="size-3" /> 聽題目</button></div><h2 className="mt-7 text-4xl font-black"><Fraction value={question.a} /> {question.op} <Fraction value={question.b} /> = ?</h2><div className="my-7 flex justify-center gap-2"><i className="size-10 rounded-full bg-[#b85b7d]" /><i className="size-10 rounded-full bg-[#b85b7d]" /><i className="size-10 rounded-full border" /><i className="size-10 rounded-full border" /></div><p>乘法：分子乘分子，分母乘分母。除法：乘以除數的倒數。</p><div className="mq-concept-choices mx-auto mt-7">{question.choices.map((choice) => <button key={choice} onClick={() => choose(choice)} disabled={result !== "idle"}><Fraction value={choice} /></button>)}</div>{result !== "idle" && <div className={`mx-auto mt-6 max-w-xl rounded-2xl border p-4 font-bold ${result === "correct" ? "border-[#0e8b87]/25 bg-[#e8f5f2] text-[#135d59]" : "border-[#f05a3c]/25 bg-[#fff0e9] text-[#8c3f2e]"}`}>{result === "correct" ? <Check className="mr-2 inline size-5" /> : <X className="mr-2 inline size-5" />}{result === "correct" ? "答對了！" : question.op === "×" ? "再試一次。先分子乘分子、分母乘分母，再約分。" : "再試一次。除以一個分數，等於乘以它的倒數。"}</div>}<div className="mt-6">{result === "correct" ? <button className="mq-start rounded-xl bg-[#f05a3c] px-5 py-3 text-white" onClick={next}>{index === 7 ? "完成挑戰" : "下一題"}</button> : result === "incorrect" ? <button className="mq-start rounded-xl bg-[#f05a3c] px-5 py-3 text-white" onClick={() => setResult("idle")}><RotateCcw className="mr-1 inline size-4" />再試一次</button> : null}</div></section></div></main>;
}
