// @ts-nocheck
import { useState } from "react";
import { Link } from "wouter";
import { recordPracticeMistake } from "@/lib/reviewRecommendations";

const equations = [["x ＋ 4 ＝ 9", "−4", "5"], ["3x ＝ 18", "÷3", "6"], ["x − 7 ＝ 3", "＋7", "10"], ["2x ＋ 3 ＝ 11", "−3，再 ÷2", "4"], ["x ÷ 5 ＝ 4", "×5", "20"], ["4x − 2 ＝ 14", "＋2，再 ÷4", "4"], ["x ＋ 12 ＝ 20", "−12", "8"], ["5x ＝ 35", "÷5", "7"]];

function WaterLab() { const [level, setLevel] = useState(45); const [objectIn, setObjectIn] = useState(false); const visible = objectIn ? Math.min(88, level + 22) : level; const displacement = objectIn ? 60 : 0; return <Lab title="3D 水位變化模擬" code="WATER LAB"><p className="text-lg font-black">把積木放進圓柱水箱，看看水位怎樣升高。</p><div className="mx-auto mt-6 flex max-w-md items-end justify-center gap-8"><div className="relative h-56 w-36 overflow-hidden rounded-b-[50%] rounded-t-[50%] border-4 border-[#172b3f] bg-white/60 shadow-[inset_0_0_0_4px_rgba(255,255,255,.5)]"><div className="absolute inset-x-0 bottom-0 bg-[#4f9fc1]/70 transition-[height] duration-500" style={{ height: `${visible}%` }}><i className="absolute -top-2 left-0 h-4 w-full rounded-[50%] bg-[#79c9e5]" /></div>{objectIn && <div className="absolute bottom-4 left-9 grid size-16 place-items-center rounded-lg border-2 border-[#172b3f] bg-[#f6be5d] text-xs font-black shadow-[7px_-7px_0_#d98c24]">積木</div>}<span className="absolute right-1 top-2 font-mono text-[10px]">{objectIn ? 260 : 200} mL</span></div><div className="text-left"><p className="font-mono text-sm font-bold text-[#f05a3c]">水位：{objectIn ? 260 : 200} mL</p><p className="mt-2 text-sm">水量上升：<b>{displacement} mL</b></p><p className="mt-1 text-sm">積木體積：<b>{displacement} cm³</b></p><button className="mt-5 rounded-xl bg-[#f05a3c] px-4 py-3 font-black text-white" onClick={() => setObjectIn(!objectIn)}>{objectIn ? "取出積木" : "放入積木"}</button></div></div><label className="mx-auto mt-6 block max-w-sm text-left text-sm font-bold">先調整原來水位：{level}%<input className="mt-2 w-full accent-[#f05a3c]" type="range" min="25" max="65" value={level} onChange={(event) => setLevel(Number(event.target.value))} /></label><p className="mt-4 rounded-xl bg-[#fff0e9] p-3 text-sm">排水法筆記：水位增加的體積＝放入物件的體積。1 mL ＝ 1 cm³。</p></Lab> }

function PieLab() { const pieces = [{ id: "teal", label: "50% · 180°", color: "#0e8b87", size: 50 }, { id: "blue", label: "25% · 90°", color: "#4f6eae", size: 25 }, { id: "yellow", label: "25% · 90°", color: "#f6be5d", size: 25 }]; const [placed, setPlaced] = useState([]); const add = (id) => setPlaced((current) => current.includes(id) ? current : [...current, id]); const total = placed.reduce((sum, id) => sum + pieces.find((item) => item.id === id).size, 0); const gradient = placed.length ? `conic-gradient(${placed.map((id, index) => { const item = pieces.find((piece) => piece.id === id); const before = placed.slice(0, index).reduce((sum, earlier) => sum + pieces.find((piece) => piece.id === earlier).size, 0); return `${item.color} ${before}% ${before + item.size}%`; }).join(",")}, #f1eee6 ${total}% 100%)` : "#f1eee6"; return <Lab title="圓形圖扇形製圖" code="PIE MAP"><p className="text-lg font-black">把三塊扇形拖到圓形圖，完成一天活動分配。</p><div className="mx-auto mt-6 grid max-w-xl gap-6 sm:grid-cols-2"><div className="space-y-3">{pieces.map((piece) => <button key={piece.id} draggable onDragStart={(event) => event.dataTransfer.setData("text/plain", piece.id)} onClick={() => add(piece.id)} className="flex w-full items-center gap-3 rounded-xl border-2 bg-white p-3 text-left font-black"><i className="size-8 rounded-full" style={{ backgroundColor: piece.color }} /><span>{piece.label}</span><small className="ml-auto text-xs text-[#617286]">拖／點</small></button>)}</div><div onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); add(event.dataTransfer.getData("text/plain")); }} className="grid min-h-56 place-items-center rounded-3xl border-4 border-dashed border-[#f05a3c] bg-[#fffaf5]"><div className="grid size-44 place-items-center rounded-full border-4 border-[#172b3f] transition-all duration-300" style={{ background: gradient }}><span className="rounded-full bg-white/90 px-3 py-1 font-mono text-xs font-black">{total}%</span></div><small className="pb-4 font-bold">CHECKPOINT · 放進圓形圖</small></div></div>{total === 100 && <p className="mt-5 rounded-xl bg-[#e8f5f2] p-3 font-bold text-[#0e8b87]">完成！半圓是 180°，四分一圓是 90°。</p>}</Lab> }

function EquationLab() { const [index, setIndex] = useState(0); const [step, setStep] = useState(""); const [value, setValue] = useState(""); const [notice, setNotice] = useState(""); const q = equations[index]; const check = () => { if (step.replaceAll(" ", "") === q[1].replaceAll(" ", "") && value === q[2]) { setNotice("好棒！兩邊做同一個運算，x 就清楚了。"); } else { setNotice("再看看：先把 x 旁邊的數移走，兩邊要做同一件事。 "); recordPracticeMistake({ key: "p6-equation-steps", grade: "P6", title: "方程逐步填答", href: location.pathname }); } }; const next = () => { setIndex(index === 7 ? 0 : index + 1); setStep(""); setValue(""); setNotice(""); }; return <Lab title="方程式逐步填答" code="EQUATION STEPS"><p className="text-2xl font-black">{q[0]}</p><div className="mx-auto mt-6 grid max-w-md gap-3 text-left"><label className="rounded-xl border-2 border-[#f05a3c]/35 bg-[#fff7ef] p-3 text-sm font-bold">第 1 步：兩邊做甚麼？<input value={step} onChange={(event) => setStep(event.target.value)} placeholder="例：−4 或 ÷3" className="mt-2 w-full rounded-lg border bg-white p-2" /></label><label className="rounded-xl border-2 border-[#4f6eae]/35 bg-[#eef5ff] p-3 text-sm font-bold">第 2 步：x ＝？<input value={value} onChange={(event) => setValue(event.target.value)} placeholder="填答案" className="mt-2 w-full rounded-lg border bg-white p-2" /></label></div><button onClick={check} className="mt-5 rounded-xl bg-[#f05a3c] px-5 py-3 font-black text-white">檢查步驟</button>{notice && <><p className="mx-auto mt-4 max-w-md rounded-xl bg-[#eff6e9] p-3 text-sm font-bold">{notice}</p>{notice.startsWith("好棒") && <button onClick={next} className="mt-3 font-bold text-[#f05a3c] underline">下一題 →</button>}</>}</Lab> }

function Lab({ title, code, children }) { return <main className="min-h-screen bg-[#f8f5ed] p-6 text-[#172b3f]"><Link href="/#path">← 返回題目庫</Link><header className="mt-7 flex flex-wrap items-center gap-3 font-mono text-xs"><b className="rounded-full bg-[#f05a3c] px-3 py-2 text-white">Q↗ P6</b><strong className="tracking-[.14em] text-[#172b3f]">MATHS QUEST</strong><span className="border-b-2 border-dotted border-[#f05a3c] pb-1">QUEST PATH · {code}</span></header><div className="mt-3 flex max-w-sm items-center gap-2 font-mono text-[9px] font-bold text-[#617286]"><span className="rounded bg-[#f05a3c] px-2 py-1 text-white">01 任務</span><i className="h-px flex-1 border-t-2 border-dotted border-[#f05a3c]"/><span>02 動手做</span><i className="h-px flex-1 border-t-2 border-dotted border-[#f05a3c]"/><span>03 CHECK</span></div><h1 className="mt-3 text-4xl font-black">{title}</h1><section className="mq-practice-card mt-6 rounded-3xl border bg-white p-7 text-center"><p className="font-mono text-xs">INTERACTIVE STATION · 動手做一做</p>{children}</section></main>; }

export default function P6InteractivePractice() { const path = location.pathname; return path.includes("water") ? <WaterLab /> : path.includes("pie") ? <PieLab /> : <EquationLab />; }
