import { Link } from "wouter";
import { useEffect, useState } from "react";
import { getReviewRecommendations, type ReviewRecord } from "@/lib/reviewRecommendations";

export default function ProgressDashboard() {
  const [items, setItems] = useState<ReviewRecord[]>(() => getReviewRecommendations(6));
  useEffect(() => { const refresh = () => setItems(getReviewRecommendations(6)); window.addEventListener("maths-quest:review-updated", refresh); return () => window.removeEventListener("maths-quest:review-updated", refresh); }, []);
  return <main className="min-h-screen bg-[#f8f5ed] p-6 text-[#172b3f]"><Link href="/">← 返回首頁</Link><header className="mt-7 max-w-4xl"><div className="flex items-center gap-3 font-mono text-xs"><b className="rounded-full bg-[#f05a3c] px-3 py-2 text-white">Q↗ MATHS QUEST</b><span className="border-b-2 border-dotted border-[#f05a3c] pb-1">REVIEW PATH · CHECKPOINT</span><span className="text-[#f05a3c]">● ┄ ┄ ○ ┄ ┄ ○</span></div><h1 className="mt-4 text-4xl font-black">個人化複習路徑</h1><p className="mt-3 max-w-xl leading-7">系統會把答錯較多、最近答錯的練習站放在前面。每次重溫，都是向下一個檢查點前進。</p></header><section className="mt-7 grid max-w-4xl gap-4 md:grid-cols-2">{items.length ? items.map((item, n) => <Link key={item.key} href={item.href} className="relative overflow-hidden rounded-3xl border bg-white p-5 shadow-[6px_6px_0_rgba(240,90,60,.12)]"><span className="absolute right-4 top-4 font-mono text-xs text-[#f05a3c]">Q-{String(n + 1).padStart(2, "0")}</span><p className="font-mono text-xs text-[#f05a3c]">REVIEW PATH · {item.grade}</p><h2 className="mt-2 text-2xl font-black">{item.title}</h2><p className="mt-3 text-sm">本機記錄：{item.misses} 次需要再練習</p><span className="mt-4 inline-block rounded-full bg-[#f05a3c] px-4 py-2 text-sm font-bold text-white">開始補強 →</span></Link>) : <div className="relative overflow-hidden rounded-3xl border border-dashed bg-white p-8 md:col-span-2"><p className="font-mono text-xs text-[#f05a3c]">Q-START · REVIEW MAP</p><div className="absolute right-6 top-6 size-24 rounded-full border border-dashed border-[#f05a3c]/40"/><div className="mt-5 flex items-center gap-3"><i className="grid size-12 place-items-center rounded-full bg-[#fff0e9] not-italic text-xl">⌁</i><span className="border-t-2 border-dotted border-[#f05a3c] flex-1"/><i className="size-4 rounded-full bg-[#f05a3c]"/></div><h2 className="mt-6 text-2xl font-black">你的複習地圖正等待第一個記號</h2><p className="mt-3 max-w-lg leading-7">完成 P1 至 P6 的練習後，答錯的題型會自動成為下一個補強檢查點。先從一個練習站出發吧。</p><Link href="/#path" className="mt-5 inline-block rounded-full bg-[#f05a3c] px-5 py-3 text-sm font-bold text-white">前往題目庫 →</Link></div>}</section></main>;
}
