import { Link } from "wouter";
import { BookOpen, Clock3, GraduationCap, ShieldCheck, UsersRound } from "lucide-react";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";

function formatDate(value: Date | string | null) { return value ? new Intl.DateTimeFormat("zh-HK", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "尚未同步"; }

export default function TeacherDashboard() {
  const { user, loading, logout } = useAuth();
  const students = trpc.teacher.managedStudents.useQuery(undefined, { enabled: user?.role === "admin" });
  if (loading) return <main className="grid min-h-screen place-items-center bg-[#172b3f] font-mono font-bold text-white">正在驗證教師帳戶…</main>;
  if (!user) return <main className="grid min-h-screen place-items-center bg-[#172b3f] p-5 text-center text-white"><section><GraduationCap className="mx-auto size-12 text-[#f6be5d]" /><h1 className="mt-4 text-3xl font-black">需要教師登入</h1><Link href="/sign-in" className="mt-5 inline-block rounded-xl bg-[#f6be5d] px-5 py-3 font-bold text-[#172b3f]">前往登入</Link></section></main>;
  if (user.role !== "admin") return <main className="grid min-h-screen place-items-center bg-[#f8f5ed] p-5 text-center text-[#172b3f]"><section><ShieldCheck className="mx-auto size-12 text-[#f05a3c]" /><h1 className="mt-4 text-3xl font-black">教師限定頁面</h1><p className="mt-3 text-[#617286]">學生帳戶不能檢視全班學生資料。</p><Link href="/account" className="mt-5 inline-block rounded-xl bg-[#172b3f] px-5 py-3 font-bold text-white">返回學生帳戶</Link></section></main>;
  return <main className="min-h-screen bg-[#edf1f7] p-5 text-[#172b3f] sm:p-8"><div className="mx-auto max-w-6xl"><header className="flex flex-wrap items-start justify-between gap-5 rounded-[28px] bg-[#172b3f] p-7 text-white"><div><p className="font-mono text-[11px] font-bold tracking-[.17em] text-[#f6be5d]">MATHS QUEST · TEACHER CONSOLE</p><h1 className="mt-3 text-4xl font-black">學生管理</h1><p className="mt-3 text-white/70">查看學生姓名、帳戶名稱、完成進度、準確度與最近雲端同步時間。</p></div><div className="flex items-center gap-3"><Link href="/" className="rounded-xl border border-white/20 px-4 py-3 text-sm font-bold">學習地圖</Link><button onClick={() => void logout()} className="rounded-xl bg-[#f6be5d] px-4 py-3 text-sm font-bold text-[#172b3f]">登出</button></div></header><section className="mt-6 grid gap-4 sm:grid-cols-3"><Metric icon={<UsersRound className="size-5 text-[#4f6eae]" />} label="REGISTERED STUDENTS" value={students.data?.length ?? "—"} detail="已註冊學生帳戶" /><Metric icon={<BookOpen className="size-5 text-[#0e8b87]" />} label="SYNC AWARE" value={students.data?.filter((student) => student.lastSyncedAt).length ?? "—"} detail="已有雲端同步紀錄" /><Metric icon={<GraduationCap className="size-5 text-[#f05a3c]" />} label="TEACHER" value={user.name || "admin"} detail="目前教師帳戶" /></section><section className="mt-6 overflow-hidden rounded-[28px] border border-[#172b3f]/12 bg-white"><div className="flex items-center justify-between border-b border-[#172b3f]/10 p-6"><div><p className="font-mono text-[10px] font-bold tracking-[.15em] text-[#4f6eae]">STUDENT DIRECTORY</p><h2 className="mt-2 text-2xl font-black">已註冊學生</h2></div><span className="rounded-full bg-[#edf1f7] px-3 py-2 text-xs font-bold">{students.data?.length ?? 0} 位</span></div>{students.data?.length ? <div className="divide-y divide-[#172b3f]/8">{students.data.map((student) => <div key={student.userId} className="grid gap-4 p-5 sm:grid-cols-[1.15fr_.75fr_.9fr] sm:items-center"><div><strong className="block text-lg">{student.nickname || student.accountName || student.username || "學生帳戶"}</strong><small className="font-mono text-[#617286]">@{student.username || "local-student"}</small></div><div><strong className="block text-2xl font-black text-[#0e8b87]">{student.accuracy === null ? "—" : `${student.accuracy}%`}</strong><small className="mt-1 block text-[#617286]">準確度 · {student.correctAnswers}/{student.answeredQuestions} 題正確</small><small className="mt-1 block text-[#617286]">完成 {student.completedPractices} 個課題</small></div><div className="flex items-center gap-2 text-sm text-[#617286]"><Clock3 className="size-4 text-[#0e8b87]" />{formatDate(student.lastSyncedAt)}</div></div>)}</div> : <p className="p-10 text-center text-[#617286]">暫時沒有學生註冊。學生建立帳戶後會自動出現在這裡。</p>}</section></div></main>;
}

function Metric({ icon, label, value, detail }: { icon: React.ReactNode; label: string; value: React.ReactNode; detail: string }) { return <div className="rounded-2xl border border-[#172b3f]/10 bg-white p-5"><div className="flex items-center gap-2">{icon}<span className="font-mono text-[10px] font-bold tracking-[.12em] text-[#617286]">{label}</span></div><strong className="mt-3 block truncate text-3xl font-black">{value}</strong><small className="mt-1 block text-[#617286]">{detail}</small></div>; }
