import { useMemo, useState } from "react";
import { BarChart3, CheckCircle2, HeartHandshake, Target } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { buildLearningSummary, type LearningGrade } from "@/lib/learningSummary";

const grades: LearningGrade[] = ["P1", "P2", "P3", "P4", "P5", "P6", "S1", "S2", "S3"];
const colors: Record<string, string> = { "數與代數": "#f05a3c", "度量": "#c8811e", "圖形與空間": "#4f6eae", "數據處理": "#0e8b87" };

export default function ParentLearningSummary() {
  const overview = trpc.learning.overview.useQuery();
  const [grade, setGrade] = useState<LearningGrade>("P1");
  const summary = useMemo(() => buildLearningSummary(overview.data?.progress, overview.data?.reviewRecords), [overview.data?.progress, overview.data?.reviewRecords]);
  const selected = summary.find((item) => item.grade === grade) ?? summary[0];
  if (!selected) return null;
  return <section className="mt-8 rounded-[30px] border border-[#172b3f]/12 bg-white p-5 shadow-[7px_7px_0_rgba(23,43,63,.05)] sm:p-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="font-mono text-[10px] font-bold tracking-[.15em] text-[#0e8b87]">FAMILY LEARNING VIEW</p><h2 className="mt-2 text-2xl font-black">和家長一起看學習地圖</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-[#617286]">按年級和課程範疇查看已完成練習站與作答準確度；這是學生帳戶內的共閱摘要，不會開啟家長後台或額外帳戶權限。</p></div><span className="inline-flex items-center gap-2 rounded-xl bg-[#e8f5f2] px-3 py-2 text-xs font-bold text-[#135d59]"><HeartHandshake className="size-4" /> 適合親子共閱</span></div><div className="mt-6 flex gap-2 overflow-x-auto pb-2">{grades.map((item) => <button key={item} onClick={() => setGrade(item)} className={`min-w-12 rounded-xl px-3 py-2 text-sm font-black transition ${grade === item ? "bg-[#172b3f] text-white" : "border border-[#172b3f]/12 bg-[#fffdf8] text-[#617286] hover:border-[#0e8b87]"}`}>{item}</button>)}</div><div className="mt-5 grid gap-4 sm:grid-cols-2"><SummaryMetric icon={<CheckCircle2 className="size-5 text-[#0e8b87]" />} label={`${selected.grade} 完成度`} value={`${selected.completionPercent}%`} detail={`${selected.completed}/${selected.total} 個課程範疇練習站`} /><SummaryMetric icon={<Target className="size-5 text-[#f05a3c]" />} label={`${selected.grade} 準確度`} value={selected.accuracy === null ? "—" : `${selected.accuracy}%`} detail={selected.attempts ? `${selected.correctAnswers}/${selected.attempts} 次作答正確` : "完成作答後會顯示"} /></div><div className="mt-5 grid gap-3 md:grid-cols-2">{selected.domains.map((domain) => <article key={domain.domain} className="rounded-2xl border border-[#172b3f]/10 bg-[#fffdf8] p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-mono text-[10px] font-bold tracking-[.12em]" style={{ color: colors[domain.domain] }}>{domain.domain}</p><strong className="mt-2 block text-xl font-black">{domain.completionPercent}% 完成</strong></div><BarChart3 className="size-5" style={{ color: colors[domain.domain] }} /></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-[#172b3f]/8"><div className="h-full rounded-full transition-[width] duration-300" style={{ width: `${domain.completionPercent}%`, backgroundColor: colors[domain.domain] }} /></div><div className="mt-3 flex justify-between text-xs font-bold text-[#617286]"><span>{domain.completed}/{domain.total} 個練習站</span><span>{domain.accuracy === null ? "尚未有作答" : `準確度 ${domain.accuracy}%`}</span></div></article>)}</div></section>;
}

function SummaryMetric({ icon, label, value, detail }: { icon: React.ReactNode; label: string; value: string; detail: string }) { return <div className="rounded-2xl border border-[#172b3f]/10 bg-[#f8f5ed] p-4"><div className="flex items-center gap-2">{icon}<p className="font-mono text-[10px] font-bold tracking-[.12em] text-[#617286]">{label}</p></div><strong className="mt-2 block text-3xl font-black">{value}</strong><small className="mt-1 block text-[#617286]">{detail}</small></div>; }
