import { useState, type FormEvent } from "react";
import { KeyRound, ShieldCheck } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";
import PasswordStrengthHint from "@/components/PasswordStrengthHint";

export default function StudentPasswordSettings() {
  const [currentPassword, setCurrentPassword] = useState("");
  const [newPassword, setNewPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const changePassword = trpc.auth.changeStudentPassword.useMutation({ onSuccess: () => { setCurrentPassword(""); setNewPassword(""); setConfirmPassword(""); toast.success("密碼已更新；其他裝置上的舊登入已安全登出。"); }, onError: (error) => toast.error(error.message) });
  const submit = (event: FormEvent) => { event.preventDefault(); if (newPassword !== confirmPassword) { toast.error("兩次輸入的新密碼不一致。"); return; } changePassword.mutate({ currentPassword, newPassword }); };
  return <section className="rounded-[28px] border border-[#172b3f]/12 bg-white p-6 shadow-[7px_7px_0_rgba(23,43,63,.05)]"><div className="flex items-start gap-3"><span className="grid size-10 place-items-center rounded-xl bg-[#e8f5f2] text-[#135d59]"><KeyRound className="size-5" /></span><div><p className="font-mono text-[10px] font-bold tracking-[.14em] text-[#0e8b87]">PASSWORD SETTINGS</p><h2 className="mt-1 text-xl font-black">更新學生密碼</h2></div></div><p className="mt-4 text-sm leading-6 text-[#617286]">使用未在其他網站使用過的長密碼。更新後，其他瀏覽器和裝置上的舊登入會失效。</p><form onSubmit={submit} className="mt-5 grid gap-4"><label><span className="text-xs font-bold text-[#617286]">目前密碼</span><input required type="password" autoComplete="current-password" value={currentPassword} onChange={(event) => setCurrentPassword(event.target.value)} maxLength={128} className="mt-2 w-full rounded-xl border border-[#172b3f]/14 bg-[#fffdf8] px-4 py-3 outline-none focus:border-[#0e8b87] focus:ring-2 focus:ring-[#0e8b87]/15" /></label><label><span className="text-xs font-bold text-[#617286]">新密碼</span><input required type="password" autoComplete="new-password" value={newPassword} onChange={(event) => setNewPassword(event.target.value)} minLength={6} maxLength={128} className="mt-2 w-full rounded-xl border border-[#172b3f]/14 bg-[#fffdf8] px-4 py-3 outline-none focus:border-[#0e8b87] focus:ring-2 focus:ring-[#0e8b87]/15" /></label><PasswordStrengthHint password={newPassword} /><label><span className="text-xs font-bold text-[#617286]">確認新密碼</span><input required type="password" autoComplete="new-password" value={confirmPassword} onChange={(event) => setConfirmPassword(event.target.value)} minLength={6} maxLength={128} className="mt-2 w-full rounded-xl border border-[#172b3f]/14 bg-[#fffdf8] px-4 py-3 outline-none focus:border-[#0e8b87] focus:ring-2 focus:ring-[#0e8b87]/15" /></label><button disabled={changePassword.isPending} className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#172b3f] px-4 py-3 text-sm font-bold text-white disabled:opacity-60"><ShieldCheck className="size-4" />{changePassword.isPending ? "正在更新…" : "安全更新密碼"}</button></form></section>;
}
