import { Bar, BarChart, CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { BarChart3, TrendingUp } from "lucide-react";

type Trends = {
  scoreTrend: { sequence: number; completedAt: Date | string; scorePercent: number }[];
  domainTrend: { domain: string; completed: number; accuracy: number | null }[];
};

function formatShortDate(value: Date | string) { return new Intl.DateTimeFormat("zh-HK", { month: "numeric", day: "numeric" }).format(new Date(value)); }

export default function TeacherLearningTrends({ trends }: { trends: Trends }) {
  const scoreData = trends.scoreTrend.map((item) => ({ ...item, label: formatShortDate(item.completedAt) }));
  const domainData = trends.domainTrend.map((item) => ({ ...item, accuracyDisplay: item.accuracy ?? 0 }));
  return <section className="mt-6 grid gap-6 lg:grid-cols-2"><TrendCard icon={<TrendingUp className="size-5 text-[#0e8b87]" />} eyebrow="SCORE TREND" title="最近成績趨勢" subtitle="以最近最多 8 個實際完成紀錄的最佳分數計算。">{scoreData.length ? <div className="h-64"><ResponsiveContainer width="100%" height="100%"><LineChart data={scoreData} margin={{ top: 12, right: 10, left: -18, bottom: 0 }}><CartesianGrid stroke="#172b3f" strokeOpacity={0.1} vertical={false} /><XAxis dataKey="label" tickLine={false} axisLine={false} tick={{ fill: "#617286", fontSize: 12 }} /><YAxis domain={[0, 100]} tickFormatter={(value) => `${value}%`} tickLine={false} axisLine={false} tick={{ fill: "#617286", fontSize: 12 }} /><Tooltip formatter={(value) => [`${value}%`, "最佳分數"]} labelFormatter={(label) => `完成日期：${label}`} /><Line type="monotone" dataKey="scorePercent" name="最佳分數" stroke="#0e8b87" strokeWidth={3} dot={{ r: 4, fill: "#f6be5d", strokeWidth: 2, stroke: "#0e8b87" }} activeDot={{ r: 6 }} /></LineChart></ResponsiveContainer></div> : <EmptyTrend label="學生尚未有足夠的完成紀錄，因此未能顯示成績趨勢。" />}</TrendCard><TrendCard icon={<BarChart3 className="size-5 text-[#4f6eae]" />} eyebrow="DOMAIN VIEW" title="學習範疇表現" subtitle="按已完成練習與錯題紀錄計算各範疇準確度。">{domainData.some((item) => item.completed > 0) ? <><div className="h-64"><ResponsiveContainer width="100%" height="100%"><BarChart data={domainData} margin={{ top: 12, right: 10, left: -18, bottom: 0 }}><CartesianGrid stroke="#172b3f" strokeOpacity={0.1} vertical={false} /><XAxis dataKey="domain" tickLine={false} axisLine={false} tick={{ fill: "#617286", fontSize: 11 }} interval={0} /><YAxis domain={[0, 100]} tickFormatter={(value) => `${value}%`} tickLine={false} axisLine={false} tick={{ fill: "#617286", fontSize: 12 }} /><Tooltip formatter={(value) => [`${value}%`, "準確度"]} /><Legend wrapperStyle={{ fontSize: 12 }} /><Bar dataKey="accuracyDisplay" name="準確度" fill="#4f6eae" radius={[7, 7, 0, 0]} /></BarChart></ResponsiveContainer></div><div className="mt-2 grid grid-cols-2 gap-2 text-xs sm:grid-cols-4">{domainData.map((item) => <div key={item.domain} className="rounded-xl bg-[#f8f5ed] px-3 py-2"><strong className="block text-[#172b3f]">{item.domain}</strong><span className="mt-1 block text-[#617286]">{item.completed} 個完成 · {item.accuracy === null ? "未有準確度" : `${item.accuracy}%`}</span></div>)}</div></> : <EmptyTrend label="學生尚未有完成練習，範疇圖表會在開始同步學習紀錄後出現。" />}</TrendCard></section>;
}

function TrendCard({ icon, eyebrow, title, subtitle, children }: { icon: React.ReactNode; eyebrow: string; title: string; subtitle: string; children: React.ReactNode }) { return <article className="overflow-hidden rounded-[28px] border border-[#172b3f]/12 bg-white"><header className="border-b border-[#172b3f]/10 p-6"><div className="flex items-center gap-2">{icon}<p className="font-mono text-[10px] font-bold tracking-[.15em] text-[#617286]">{eyebrow}</p></div><h2 className="mt-2 text-xl font-black">{title}</h2><p className="mt-2 text-sm leading-6 text-[#617286]">{subtitle}</p></header><div className="p-6">{children}</div></article>; }
function EmptyTrend({ label }: { label: string }) { return <p className="rounded-xl bg-[#f8f5ed] p-5 text-center text-sm leading-6 text-[#617286]">{label}</p>; }
